DROP DATABASE IF EXISTS talktome;

CREATE DATABASE IF NOT EXISTS talktome

DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE talktome;

CREATE TABLE IF NOT EXISTS member (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    profile_id INT DEFAULT NULL,
    region VARCHAR(20) NOT NULL,
    intro LONGTEXT DEFAULT NULL,
    latitude DOUBLE DEFAULT NULL,
    longitude DOUBLE DEFAULT NULL,
    platform VARCHAR(50) DEFAULT NULL,
    message VARCHAR(700) DEFAULT NULL,
    fcm_token VARCHAR(500) DEFAULT NULL,
    receive_fcm BOOLEAN NOT NULL,
    is_blocked BOOLEAN NOT NULL,
    device_id VARCHAR(100) NOT NULL,
    recent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_size INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS image (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    seq TINYINT NOT NULL,
	image_id INT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS block (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    me_id INT NOT NULL,
    block_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friend (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    me_id INT NOT NULL,
    partner_id INT NOT NULL,
    message VARCHAR(500) DEFAULT NULL,
    permit BOOLEAN DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    room_id INT NOT NULL,
    user_id INT NOT NULL,
    content VARCHAR(255) DEFAULT NULL,
    read_check BOOLEAN DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room (
	room_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    me_id INT NOT NULL,
    partner_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notice (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message LONGTEXT NOT NULL,
    open BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_devices (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    request_id INT NOT NULL,
    member_id INT NOT NULL,
    device_id VARCHAR(100) NOT NULL,
    reason VARCHAR(300) DEFAULT NULL,
    apply BOOLEAN NOT NULL,
    blocked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- SHOW VARIABLES LIKE 'max_connections';

-- DELETE FROM member;

-- DROP USER 'seungmin'@'localhost';

-- CREATE USER 'seungmin'@'localhost' identified by '1111';

-- GRANT ALL PRIVILEGES ON talktome.* to 'seungmin'@'localhost';

-- FLUSH PRIVILEGES;

-- show grants for 'seungmin'@'localhost';